export const ENCLAVE_REGISTRY_ABI = [
  {
    inputs: [
      { internalType: "address", name: "initialOwner", type: "address" },
      { internalType: "contract IFdcVerification", name: "_fdcVerification", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [{ internalType: "address", name: "vault", type: "address" }],
    name: "AlreadyRegistered",
    type: "error",
  },
  { inputs: [], name: "AttestationMismatch", type: "error" },
  { inputs: [], name: "InvalidAttestationProof", type: "error" },
  {
    inputs: [{ internalType: "address", name: "vault", type: "address" }],
    name: "NotRegistered",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "vault", type: "address" },
      { indexed: true, internalType: "address", name: "revokedSigner", type: "address" },
    ],
    name: "EnclaveEmergencyRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "vault", type: "address" },
      { indexed: true, internalType: "address", name: "signer", type: "address" },
    ],
    name: "EnclaveRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "vault", type: "address" },
      { indexed: true, internalType: "address", name: "oldSigner", type: "address" },
      { indexed: true, internalType: "address", name: "newSigner", type: "address" },
    ],
    name: "EnclaveRotated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "vault", type: "address" }],
    name: "emergencyRevoke",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "fdcVerification",
    outputs: [{ internalType: "contract IFdcVerification", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "vault", type: "address" },
      { internalType: "address", name: "signer", type: "address" },
    ],
    name: "isValidSigner",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingOwner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "vault", type: "address" },
      { internalType: "address", name: "enclaveSigner", type: "address" },
      {
        components: [
          { internalType: "bytes32[]", name: "merkleProof", type: "bytes32[]" },
          {
            components: [
              { internalType: "bytes32", name: "attestationType", type: "bytes32" },
              { internalType: "bytes32", name: "sourceId", type: "bytes32" },
              { internalType: "uint64", name: "votingRound", type: "uint64" },
              { internalType: "uint64", name: "lowestUsedTimestamp", type: "uint64" },
              {
                components: [
                  { internalType: "string", name: "url", type: "string" },
                  { internalType: "string", name: "httpMethod", type: "string" },
                  { internalType: "string", name: "headers", type: "string" },
                  { internalType: "string", name: "queryParams", type: "string" },
                  { internalType: "string", name: "body", type: "string" },
                  { internalType: "string", name: "postProcessJq", type: "string" },
                  { internalType: "string", name: "abiSignature", type: "string" },
                ],
                internalType: "struct IWeb2Json.RequestBody",
                name: "requestBody",
                type: "tuple",
              },
              {
                components: [{ internalType: "bytes", name: "abiEncodedData", type: "bytes" }],
                internalType: "struct IWeb2Json.ResponseBody",
                name: "responseBody",
                type: "tuple",
              },
            ],
            internalType: "struct IWeb2Json.Response",
            name: "data",
            type: "tuple",
          },
        ],
        internalType: "struct IWeb2Json.Proof",
        name: "proof",
        type: "tuple",
      },
    ],
    name: "registerEnclave",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "vault", type: "address" },
      { internalType: "address", name: "newSigner", type: "address" },
      {
        components: [
          { internalType: "bytes32[]", name: "merkleProof", type: "bytes32[]" },
          {
            components: [
              { internalType: "bytes32", name: "attestationType", type: "bytes32" },
              { internalType: "bytes32", name: "sourceId", type: "bytes32" },
              { internalType: "uint64", name: "votingRound", type: "uint64" },
              { internalType: "uint64", name: "lowestUsedTimestamp", type: "uint64" },
              {
                components: [
                  { internalType: "string", name: "url", type: "string" },
                  { internalType: "string", name: "httpMethod", type: "string" },
                  { internalType: "string", name: "headers", type: "string" },
                  { internalType: "string", name: "queryParams", type: "string" },
                  { internalType: "string", name: "body", type: "string" },
                  { internalType: "string", name: "postProcessJq", type: "string" },
                  { internalType: "string", name: "abiSignature", type: "string" },
                ],
                internalType: "struct IWeb2Json.RequestBody",
                name: "requestBody",
                type: "tuple",
              },
              {
                components: [{ internalType: "bytes", name: "abiEncodedData", type: "bytes" }],
                internalType: "struct IWeb2Json.ResponseBody",
                name: "responseBody",
                type: "tuple",
              },
            ],
            internalType: "struct IWeb2Json.Response",
            name: "data",
            type: "tuple",
          },
        ],
        internalType: "struct IWeb2Json.Proof",
        name: "proof",
        type: "tuple",
      },
    ],
    name: "rotateEnclaveSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "vault", type: "address" }],
    name: "signerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
