/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategistRouteImport } from './routes/strategist'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultsIndexRouteImport } from './routes/vaults.index'
import { Route as VaultsIdRouteImport } from './routes/vaults.$id'

const StrategistRoute = StrategistRouteImport.update({
  id: '/strategist',
  path: '/strategist',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIndexRoute = VaultsIndexRouteImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIdRoute = VaultsIdRouteImport.update({
  id: '/vaults/$id',
  path: '/vaults/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deploy': typeof DeployRoute
  '/strategist': typeof StrategistRoute
  '/vaults/$id': typeof VaultsIdRoute
  '/vaults/': typeof VaultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deploy': typeof DeployRoute
  '/strategist': typeof StrategistRoute
  '/vaults/$id': typeof VaultsIdRoute
  '/vaults': typeof VaultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deploy': typeof DeployRoute
  '/strategist': typeof StrategistRoute
  '/vaults/$id': typeof VaultsIdRoute
  '/vaults/': typeof VaultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/deploy' | '/strategist' | '/vaults/$id' | '/vaults/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/deploy' | '/strategist' | '/vaults/$id' | '/vaults'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/deploy'
    | '/strategist'
    | '/vaults/$id'
    | '/vaults/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DeployRoute: typeof DeployRoute
  StrategistRoute: typeof StrategistRoute
  VaultsIdRoute: typeof VaultsIdRoute
  VaultsIndexRoute: typeof VaultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategist': {
      id: '/strategist'
      path: '/strategist'
      fullPath: '/strategist'
      preLoaderRoute: typeof StrategistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/': {
      id: '/vaults/'
      path: '/vaults'
      fullPath: '/vaults/'
      preLoaderRoute: typeof VaultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/$id': {
      id: '/vaults/$id'
      path: '/vaults/$id'
      fullPath: '/vaults/$id'
      preLoaderRoute: typeof VaultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DeployRoute: DeployRoute,
  StrategistRoute: StrategistRoute,
  VaultsIdRoute: VaultsIdRoute,
  VaultsIndexRoute: VaultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
